// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Center struct {
	AdminListen string

	ChatCheckMd5 bool

	ChatDefaultExpireTime int

	ChatDefaultHotExpireTime int

	ChatroomBroadcastPolicy int

	ChatroomDegradeMembers int

	ChatroomDegradePolicy int

	ChatroomDiscardMessages map[int]int

	ChatroomMessagePolicy map[int]int

	CrDropMsgsDtDefault map[int]int

	CrDropMsgsDtPolicy string

	GorpcListen string

	Listen string

	Loglevel int

	MaxMsgSize int

	MessageMaxDelay int

	MessageSendInterval string

	MultiListen []string

	OnlineBroadcastPolicy int

	QpsCountInterval int

	QpsLimits map[string]int

	ResponseSlowThreshold int64

	SendPublicNotificationAfter int

	ShardId int

	SpecialMessageType map[string]struct{}

	StatResponseTime bool

	StoreImOutbox int
}

var CenterPtr unsafe.Pointer = unsafe.Pointer(&Center{})

func CurrentCenter() *Center {
	return (*Center)(atomic.LoadPointer(&CenterPtr))
}

func UpdateCenter(v *Center) {
	atomic.StorePointer(&CenterPtr, unsafe.Pointer(v))
}
