// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Dispatcher struct {
	AdminListen string

	GatewayWeight map[string]int

	GorpcListen string

	Listen string

	Loglevel int

	MaxGateways int

	NeedSign bool

	PrivateKey string

	SslListen string

	StatInterval int

	WhiteListAddr map[string]int

	WhiteListUser map[string]struct{}

	ZoneGatewayweight map[string][]string
}

var DispatcherPtr unsafe.Pointer = unsafe.Pointer(&Dispatcher{})

func CurrentDispatcher() *Dispatcher {
	return (*Dispatcher)(atomic.LoadPointer(&DispatcherPtr))
}

func UpdateDispatcher(v *Dispatcher) {
	atomic.StorePointer(&DispatcherPtr, unsafe.Pointer(v))
}
