// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Gateway struct {
	AdminListen string

	ChatroomMsgNormalThreshold int64

	ChatroomMsgSlowThreshold int64

	GorpcListen string

	IgnoreWebsocket bool

	Listen string

	Loglevel int

	Manager string

	MultiListen []string

	OperationSlowThreshold int64

	QpsCountInterval int

	ResponseSlowThreshold int64

	StatResponseTime bool

	TagCleanDuration int

	TagConsumerChanLen int64

	TagConsumerCount int64
}

var GatewayPtr unsafe.Pointer = unsafe.Pointer(&Gateway{})

func CurrentGateway() *Gateway {
	return (*Gateway)(atomic.LoadPointer(&GatewayPtr))
}

func UpdateGateway(v *Gateway) {
	atomic.StorePointer(&GatewayPtr, unsafe.Pointer(v))
}
