// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Global struct {
	ApnsRpcs []string

	Appids []string

	BigRoom map[string]struct{}

	CenterRpcs []string

	Cluster string

	CoordinatorArea map[string][]string

	CoordinatorRpcs []string

	Debug bool

	DefaultKeys map[string]string

	GatewayRpcs []string

	GatewayRpcsSr map[string][]string

	GroupSaverRpcs []string

	NewChatroomSend bool

	PullLost map[string]bool

	RouterRpcs []string

	SaverRpcs []string

	SessionRpcs []string

	StaticRoomCoordinator map[string][]string

	WhiteList map[string]struct{}
}

var GlobalPtr unsafe.Pointer = unsafe.Pointer(&Global{})

func CurrentGlobal() *Global {
	return (*Global)(atomic.LoadPointer(&GlobalPtr))
}

func UpdateGlobal(v *Global) {
	atomic.StorePointer(&GlobalPtr, unsafe.Pointer(v))
}
