// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Router struct {
	AdminListen string

	BlackIp map[string]bool

	CallbackConnTimeout int64

	CallbackDisable bool

	CallbackMaxIdleConns int

	CallbackTimeout int64

	CallbackUrl map[string]string

	CheckAppUser bool

	CheckWebUser bool

	DisableEncrypt bool

	DoOperationsConsumerChanlen int

	DoOperationsConsumerCount int

	GorpcListen string

	GorpcSaverClientTimeout map[string]string

	IgnoreChatroomErrors bool

	Loglevel int

	MaxPullMessage int

	PushDegrade map[string]int

	PushDegradeAll bool

	PushDegradeUsers map[string]struct{}

	QpsCountInterval int

	QueryAfterSeconds int

	SendPublicRandMax int

	SendPublicRandMin int

	StatResponseTime bool

	WebConnectionTypes map[string]struct{}
}

var RouterPtr unsafe.Pointer = unsafe.Pointer(&Router{})

func CurrentRouter() *Router {
	return (*Router)(atomic.LoadPointer(&RouterPtr))
}

func UpdateRouter(v *Router) {
	atomic.StorePointer(&RouterPtr, unsafe.Pointer(v))
}
