// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Saver struct {
	AdminListen string

	AlternativeMessageMongo []string

	AlternativeMessageMongoPorts []string

	AppidTablesSuffix map[int]string

	CacheChatroomMessageConsumerChanlen int

	CacheChatroomMessageConsumerCount int

	ChatroomGatewaysDegrade bool

	ChatroomMembersDegrade bool

	ChatroomMessageAddrs []string

	ChatroomMessageTimeout int64

	DefaultExpire int

	GorpcListen string

	Loglevel int

	MaxPublicCache int

	MaxSessionSummary int

	MessageMongo []string

	MessageMongoPorts []string

	MessageRedis []string

	MessageStore int

	MongoTimeout int64

	QpsCountInterval int

	ReloadPublicInterval int

	ResponseSlowThreshold int64

	SessionAddrs []string

	SessionCheckInterval int

	StatResponseTime bool
}

var SaverPtr unsafe.Pointer = unsafe.Pointer(&Saver{})

func CurrentSaver() *Saver {
	return (*Saver)(atomic.LoadPointer(&SaverPtr))
}

func UpdateSaver(v *Saver) {
	atomic.StorePointer(&SaverPtr, unsafe.Pointer(v))
}
