// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Session struct {
	AdminListen string

	CallbackConnTimeout int64

	CallbackDegradeQps int

	CallbackMaxIdleConns int

	CallbackTimeout int64

	ChatRoomMinDuration int

	ChatRoomTimerHour int

	ChatRoomTimerMinute int

	ChatroomCallbackUrl map[string]string

	ChatroomNotifyPolicy map[int]int

	GorpcListen string

	Loglevel int

	OnlineCacheCap int

	OnlineCacheExpire int

	OnlineCacheSlot int

	PostponeCallbackDuration int

	QpsCountInterval int

	ResponseSlowThreshold int64

	SessionTimerHour int

	SessionTimerMinute int

	StatResponseTime bool
}

var SessionPtr unsafe.Pointer = unsafe.Pointer(&Session{})

func CurrentSession() *Session {
	return (*Session)(atomic.LoadPointer(&SessionPtr))
}

func UpdateSession(v *Session) {
	atomic.StorePointer(&SessionPtr, unsafe.Pointer(v))
}
