// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.huajiao.comm.protobuf;

public final class GroupChatProto {
  private GroupChatProto() {}
  @SuppressWarnings("hiding")
  public static final class GroupNotify extends
      com.google.protobuf.micro.MessageMicro {
    public GroupNotify() {}

    // required string groupid = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private boolean hasGroupid;
    private java.lang.String groupid_ = "";
    public java.lang.String getGroupid() { return groupid_; }
    public boolean hasGroupid() { return hasGroupid; }
    public GroupNotify setGroupid(java.lang.String value) {
      hasGroupid = true;
      groupid_ = value;
      return this;
    }
    public GroupNotify clearGroupid() {
      hasGroupid = false;
      groupid_ = "";
      return this;
    }

    // required uint64 msgid = 2;
    public static final int MSGID_FIELD_NUMBER = 2;
    private boolean hasMsgid;
    private long msgid_ = 0L;
    public long getMsgid() { return msgid_; }
    public boolean hasMsgid() { return hasMsgid; }
    public GroupNotify setMsgid(long value) {
      hasMsgid = true;
      msgid_ = value;
      return this;
    }
    public GroupNotify clearMsgid() {
      hasMsgid = false;
      msgid_ = 0L;
      return this;
    }

    // optional string summary = 3;
    public static final int SUMMARY_FIELD_NUMBER = 3;
    private boolean hasSummary;
    private java.lang.String summary_ = "";
    public java.lang.String getSummary() { return summary_; }
    public boolean hasSummary() { return hasSummary; }
    public GroupNotify setSummary(java.lang.String value) {
      hasSummary = true;
      summary_ = value;
      return this;
    }
    public GroupNotify clearSummary() {
      hasSummary = false;
      summary_ = "";
      return this;
    }

    public final GroupNotify clear() {
      clearGroupid();
      clearMsgid();
      clearSummary();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGroupid) return false;
      if (!hasMsgid) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasGroupid()) {
        output.writeString(1, getGroupid());
      }
      if (hasMsgid()) {
        output.writeUInt64(2, getMsgid());
      }
      if (hasSummary()) {
        output.writeString(3, getSummary());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasGroupid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getGroupid());
      }
      if (hasMsgid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(2, getMsgid());
      }
      if (hasSummary()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(3, getSummary());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GroupNotify mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setGroupid(input.readString());
            break;
          }
          case 16: {
            setMsgid(input.readUInt64());
            break;
          }
          case 26: {
            setSummary(input.readString());
            break;
          }
        }
      }
    }

    public static GroupNotify parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GroupNotify) (new GroupNotify().mergeFrom(data));
    }

    public static GroupNotify parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GroupNotify().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GroupMessageReq extends
      com.google.protobuf.micro.MessageMicro {
    public GroupMessageReq() {}

    // required string groupid = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private boolean hasGroupid;
    private java.lang.String groupid_ = "";
    public java.lang.String getGroupid() { return groupid_; }
    public boolean hasGroupid() { return hasGroupid; }
    public GroupMessageReq setGroupid(java.lang.String value) {
      hasGroupid = true;
      groupid_ = value;
      return this;
    }
    public GroupMessageReq clearGroupid() {
      hasGroupid = false;
      groupid_ = "";
      return this;
    }

    // required string traceid = 2;
    public static final int TRACEID_FIELD_NUMBER = 2;
    private boolean hasTraceid;
    private java.lang.String traceid_ = "";
    public java.lang.String getTraceid() { return traceid_; }
    public boolean hasTraceid() { return hasTraceid; }
    public GroupMessageReq setTraceid(java.lang.String value) {
      hasTraceid = true;
      traceid_ = value;
      return this;
    }
    public GroupMessageReq clearTraceid() {
      hasTraceid = false;
      traceid_ = "";
      return this;
    }

    // optional uint64 startid = 3;
    public static final int STARTID_FIELD_NUMBER = 3;
    private boolean hasStartid;
    private long startid_ = 0L;
    public long getStartid() { return startid_; }
    public boolean hasStartid() { return hasStartid; }
    public GroupMessageReq setStartid(long value) {
      hasStartid = true;
      startid_ = value;
      return this;
    }
    public GroupMessageReq clearStartid() {
      hasStartid = false;
      startid_ = 0L;
      return this;
    }

    // optional int32 offset = 4;
    public static final int OFFSET_FIELD_NUMBER = 4;
    private boolean hasOffset;
    private int offset_ = 0;
    public int getOffset() { return offset_; }
    public boolean hasOffset() { return hasOffset; }
    public GroupMessageReq setOffset(int value) {
      hasOffset = true;
      offset_ = value;
      return this;
    }
    public GroupMessageReq clearOffset() {
      hasOffset = false;
      offset_ = 0;
      return this;
    }

    public final GroupMessageReq clear() {
      clearGroupid();
      clearTraceid();
      clearStartid();
      clearOffset();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGroupid) return false;
      if (!hasTraceid) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasGroupid()) {
        output.writeString(1, getGroupid());
      }
      if (hasTraceid()) {
        output.writeString(2, getTraceid());
      }
      if (hasStartid()) {
        output.writeUInt64(3, getStartid());
      }
      if (hasOffset()) {
        output.writeInt32(4, getOffset());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasGroupid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getGroupid());
      }
      if (hasTraceid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getTraceid());
      }
      if (hasStartid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(3, getStartid());
      }
      if (hasOffset()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt32Size(4, getOffset());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GroupMessageReq mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setGroupid(input.readString());
            break;
          }
          case 18: {
            setTraceid(input.readString());
            break;
          }
          case 24: {
            setStartid(input.readUInt64());
            break;
          }
          case 32: {
            setOffset(input.readInt32());
            break;
          }
        }
      }
    }

    public static GroupMessageReq parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GroupMessageReq) (new GroupMessageReq().mergeFrom(data));
    }

    public static GroupMessageReq parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GroupMessageReq().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GroupMessage extends
      com.google.protobuf.micro.MessageMicro {
    public GroupMessage() {}

    // required uint64 msgid = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private boolean hasMsgid;
    private long msgid_ = 0L;
    public long getMsgid() { return msgid_; }
    public boolean hasMsgid() { return hasMsgid; }
    public GroupMessage setMsgid(long value) {
      hasMsgid = true;
      msgid_ = value;
      return this;
    }
    public GroupMessage clearMsgid() {
      hasMsgid = false;
      msgid_ = 0L;
      return this;
    }

    // required string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private boolean hasContent;
    private java.lang.String content_ = "";
    public java.lang.String getContent() { return content_; }
    public boolean hasContent() { return hasContent; }
    public GroupMessage setContent(java.lang.String value) {
      hasContent = true;
      content_ = value;
      return this;
    }
    public GroupMessage clearContent() {
      hasContent = false;
      content_ = "";
      return this;
    }

    // optional int64 sendtime = 3;
    public static final int SENDTIME_FIELD_NUMBER = 3;
    private boolean hasSendtime;
    private long sendtime_ = 0L;
    public long getSendtime() { return sendtime_; }
    public boolean hasSendtime() { return hasSendtime; }
    public GroupMessage setSendtime(long value) {
      hasSendtime = true;
      sendtime_ = value;
      return this;
    }
    public GroupMessage clearSendtime() {
      hasSendtime = false;
      sendtime_ = 0L;
      return this;
    }

    // optional string sender = 4;
    public static final int SENDER_FIELD_NUMBER = 4;
    private boolean hasSender;
    private java.lang.String sender_ = "";
    public java.lang.String getSender() { return sender_; }
    public boolean hasSender() { return hasSender; }
    public GroupMessage setSender(java.lang.String value) {
      hasSender = true;
      sender_ = value;
      return this;
    }
    public GroupMessage clearSender() {
      hasSender = false;
      sender_ = "";
      return this;
    }

    public final GroupMessage clear() {
      clearMsgid();
      clearContent();
      clearSendtime();
      clearSender();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasMsgid) return false;
      if (!hasContent) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasMsgid()) {
        output.writeUInt64(1, getMsgid());
      }
      if (hasContent()) {
        output.writeString(2, getContent());
      }
      if (hasSendtime()) {
        output.writeInt64(3, getSendtime());
      }
      if (hasSender()) {
        output.writeString(4, getSender());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasMsgid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(1, getMsgid());
      }
      if (hasContent()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getContent());
      }
      if (hasSendtime()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt64Size(3, getSendtime());
      }
      if (hasSender()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(4, getSender());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GroupMessage mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            setMsgid(input.readUInt64());
            break;
          }
          case 18: {
            setContent(input.readString());
            break;
          }
          case 24: {
            setSendtime(input.readInt64());
            break;
          }
          case 34: {
            setSender(input.readString());
            break;
          }
        }
      }
    }

    public static GroupMessage parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GroupMessage) (new GroupMessage().mergeFrom(data));
    }

    public static GroupMessage parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GroupMessage().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GroupMessageResp extends
      com.google.protobuf.micro.MessageMicro {
    public GroupMessageResp() {}

    // required string groupid = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private boolean hasGroupid;
    private java.lang.String groupid_ = "";
    public java.lang.String getGroupid() { return groupid_; }
    public boolean hasGroupid() { return hasGroupid; }
    public GroupMessageResp setGroupid(java.lang.String value) {
      hasGroupid = true;
      groupid_ = value;
      return this;
    }
    public GroupMessageResp clearGroupid() {
      hasGroupid = false;
      groupid_ = "";
      return this;
    }

    // required string traceid = 2;
    public static final int TRACEID_FIELD_NUMBER = 2;
    private boolean hasTraceid;
    private java.lang.String traceid_ = "";
    public java.lang.String getTraceid() { return traceid_; }
    public boolean hasTraceid() { return hasTraceid; }
    public GroupMessageResp setTraceid(java.lang.String value) {
      hasTraceid = true;
      traceid_ = value;
      return this;
    }
    public GroupMessageResp clearTraceid() {
      hasTraceid = false;
      traceid_ = "";
      return this;
    }

    // repeated .pb.GroupMessage msglist = 3;
    public static final int MSGLIST_FIELD_NUMBER = 3;
    private java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupMessage> msglist_ =
      java.util.Collections.emptyList();
    public java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupMessage> getMsglistList() {
      return msglist_;
    }
    public int getMsglistCount() { return msglist_.size(); }
    public com.huajiao.comm.protobuf.GroupChatProto.GroupMessage getMsglist(int index) {
      return msglist_.get(index);
    }
    public GroupMessageResp setMsglist(int index, com.huajiao.comm.protobuf.GroupChatProto.GroupMessage value) {
      if (value == null) {
        throw new NullPointerException();
      }
      msglist_.set(index, value);
      return this;
    }
    public GroupMessageResp addMsglist(com.huajiao.comm.protobuf.GroupChatProto.GroupMessage value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (msglist_.isEmpty()) {
        msglist_ = new java.util.ArrayList<com.huajiao.comm.protobuf.GroupChatProto.GroupMessage>();
      }
      msglist_.add(value);
      return this;
    }
    public GroupMessageResp clearMsglist() {
      msglist_ = java.util.Collections.emptyList();
      return this;
    }

    // optional uint64 maxid = 4;
    public static final int MAXID_FIELD_NUMBER = 4;
    private boolean hasMaxid;
    private long maxid_ = 0L;
    public long getMaxid() { return maxid_; }
    public boolean hasMaxid() { return hasMaxid; }
    public GroupMessageResp setMaxid(long value) {
      hasMaxid = true;
      maxid_ = value;
      return this;
    }
    public GroupMessageResp clearMaxid() {
      hasMaxid = false;
      maxid_ = 0L;
      return this;
    }

    // optional int64 version = 5;
    public static final int VERSION_FIELD_NUMBER = 5;
    private boolean hasVersion;
    private long version_ = 0L;
    public long getVersion() { return version_; }
    public boolean hasVersion() { return hasVersion; }
    public GroupMessageResp setVersion(long value) {
      hasVersion = true;
      version_ = value;
      return this;
    }
    public GroupMessageResp clearVersion() {
      hasVersion = false;
      version_ = 0L;
      return this;
    }

    public final GroupMessageResp clear() {
      clearGroupid();
      clearTraceid();
      clearMsglist();
      clearMaxid();
      clearVersion();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGroupid) return false;
      if (!hasTraceid) return false;
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessage element : getMsglistList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasGroupid()) {
        output.writeString(1, getGroupid());
      }
      if (hasTraceid()) {
        output.writeString(2, getTraceid());
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessage element : getMsglistList()) {
        output.writeMessage(3, element);
      }
      if (hasMaxid()) {
        output.writeUInt64(4, getMaxid());
      }
      if (hasVersion()) {
        output.writeInt64(5, getVersion());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasGroupid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getGroupid());
      }
      if (hasTraceid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(2, getTraceid());
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessage element : getMsglistList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(3, element);
      }
      if (hasMaxid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(4, getMaxid());
      }
      if (hasVersion()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt64Size(5, getVersion());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GroupMessageResp mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setGroupid(input.readString());
            break;
          }
          case 18: {
            setTraceid(input.readString());
            break;
          }
          case 26: {
            com.huajiao.comm.protobuf.GroupChatProto.GroupMessage value = new com.huajiao.comm.protobuf.GroupChatProto.GroupMessage();
            input.readMessage(value);
            addMsglist(value);
            break;
          }
          case 32: {
            setMaxid(input.readUInt64());
            break;
          }
          case 40: {
            setVersion(input.readInt64());
            break;
          }
        }
      }
    }

    public static GroupMessageResp parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GroupMessageResp) (new GroupMessageResp().mergeFrom(data));
    }

    public static GroupMessageResp parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GroupMessageResp().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GroupSyncReq extends
      com.google.protobuf.micro.MessageMicro {
    public GroupSyncReq() {}

    // required string groupid = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private boolean hasGroupid;
    private java.lang.String groupid_ = "";
    public java.lang.String getGroupid() { return groupid_; }
    public boolean hasGroupid() { return hasGroupid; }
    public GroupSyncReq setGroupid(java.lang.String value) {
      hasGroupid = true;
      groupid_ = value;
      return this;
    }
    public GroupSyncReq clearGroupid() {
      hasGroupid = false;
      groupid_ = "";
      return this;
    }

    public final GroupSyncReq clear() {
      clearGroupid();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGroupid) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasGroupid()) {
        output.writeString(1, getGroupid());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasGroupid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getGroupid());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GroupSyncReq mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setGroupid(input.readString());
            break;
          }
        }
      }
    }

    public static GroupSyncReq parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GroupSyncReq) (new GroupSyncReq().mergeFrom(data));
    }

    public static GroupSyncReq parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GroupSyncReq().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GroupInfo extends
      com.google.protobuf.micro.MessageMicro {
    public GroupInfo() {}

    // required string groupid = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private boolean hasGroupid;
    private java.lang.String groupid_ = "";
    public java.lang.String getGroupid() { return groupid_; }
    public boolean hasGroupid() { return hasGroupid; }
    public GroupInfo setGroupid(java.lang.String value) {
      hasGroupid = true;
      groupid_ = value;
      return this;
    }
    public GroupInfo clearGroupid() {
      hasGroupid = false;
      groupid_ = "";
      return this;
    }

    // optional uint64 maxid = 2;
    public static final int MAXID_FIELD_NUMBER = 2;
    private boolean hasMaxid;
    private long maxid_ = 0L;
    public long getMaxid() { return maxid_; }
    public boolean hasMaxid() { return hasMaxid; }
    public GroupInfo setMaxid(long value) {
      hasMaxid = true;
      maxid_ = value;
      return this;
    }
    public GroupInfo clearMaxid() {
      hasMaxid = false;
      maxid_ = 0L;
      return this;
    }

    // optional int64 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private boolean hasVersion;
    private long version_ = 0L;
    public long getVersion() { return version_; }
    public boolean hasVersion() { return hasVersion; }
    public GroupInfo setVersion(long value) {
      hasVersion = true;
      version_ = value;
      return this;
    }
    public GroupInfo clearVersion() {
      hasVersion = false;
      version_ = 0L;
      return this;
    }

    // optional uint64 startid = 4;
    public static final int STARTID_FIELD_NUMBER = 4;
    private boolean hasStartid;
    private long startid_ = 0L;
    public long getStartid() { return startid_; }
    public boolean hasStartid() { return hasStartid; }
    public GroupInfo setStartid(long value) {
      hasStartid = true;
      startid_ = value;
      return this;
    }
    public GroupInfo clearStartid() {
      hasStartid = false;
      startid_ = 0L;
      return this;
    }

    public final GroupInfo clear() {
      clearGroupid();
      clearMaxid();
      clearVersion();
      clearStartid();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasGroupid) return false;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasGroupid()) {
        output.writeString(1, getGroupid());
      }
      if (hasMaxid()) {
        output.writeUInt64(2, getMaxid());
      }
      if (hasVersion()) {
        output.writeInt64(3, getVersion());
      }
      if (hasStartid()) {
        output.writeUInt64(4, getStartid());
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasGroupid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(1, getGroupid());
      }
      if (hasMaxid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(2, getMaxid());
      }
      if (hasVersion()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt64Size(3, getVersion());
      }
      if (hasStartid()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt64Size(4, getStartid());
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GroupInfo mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            setGroupid(input.readString());
            break;
          }
          case 16: {
            setMaxid(input.readUInt64());
            break;
          }
          case 24: {
            setVersion(input.readInt64());
            break;
          }
          case 32: {
            setStartid(input.readUInt64());
            break;
          }
        }
      }
    }

    public static GroupInfo parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GroupInfo) (new GroupInfo().mergeFrom(data));
    }

    public static GroupInfo parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GroupInfo().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GroupUpPacket extends
      com.google.protobuf.micro.MessageMicro {
    public GroupUpPacket() {}

    // required uint32 payload = 1;
    public static final int PAYLOAD_FIELD_NUMBER = 1;
    private boolean hasPayload;
    private int payload_ = 0;
    public int getPayload() { return payload_; }
    public boolean hasPayload() { return hasPayload; }
    public GroupUpPacket setPayload(int value) {
      hasPayload = true;
      payload_ = value;
      return this;
    }
    public GroupUpPacket clearPayload() {
      hasPayload = false;
      payload_ = 0;
      return this;
    }

    // repeated .pb.GroupSyncReq syncreq = 6;
    public static final int SYNCREQ_FIELD_NUMBER = 6;
    private java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq> syncreq_ =
      java.util.Collections.emptyList();
    public java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq> getSyncreqList() {
      return syncreq_;
    }
    public int getSyncreqCount() { return syncreq_.size(); }
    public com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq getSyncreq(int index) {
      return syncreq_.get(index);
    }
    public GroupUpPacket setSyncreq(int index, com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq value) {
      if (value == null) {
        throw new NullPointerException();
      }
      syncreq_.set(index, value);
      return this;
    }
    public GroupUpPacket addSyncreq(com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (syncreq_.isEmpty()) {
        syncreq_ = new java.util.ArrayList<com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq>();
      }
      syncreq_.add(value);
      return this;
    }
    public GroupUpPacket clearSyncreq() {
      syncreq_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated .pb.GroupMessageReq getmsgreq = 7;
    public static final int GETMSGREQ_FIELD_NUMBER = 7;
    private java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq> getmsgreq_ =
      java.util.Collections.emptyList();
    public java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq> getGetmsgreqList() {
      return getmsgreq_;
    }
    public int getGetmsgreqCount() { return getmsgreq_.size(); }
    public com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq getGetmsgreq(int index) {
      return getmsgreq_.get(index);
    }
    public GroupUpPacket setGetmsgreq(int index, com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq value) {
      if (value == null) {
        throw new NullPointerException();
      }
      getmsgreq_.set(index, value);
      return this;
    }
    public GroupUpPacket addGetmsgreq(com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (getmsgreq_.isEmpty()) {
        getmsgreq_ = new java.util.ArrayList<com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq>();
      }
      getmsgreq_.add(value);
      return this;
    }
    public GroupUpPacket clearGetmsgreq() {
      getmsgreq_ = java.util.Collections.emptyList();
      return this;
    }

    public final GroupUpPacket clear() {
      clearPayload();
      clearSyncreq();
      clearGetmsgreq();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasPayload) return false;
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq element : getSyncreqList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq element : getGetmsgreqList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasPayload()) {
        output.writeUInt32(1, getPayload());
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq element : getSyncreqList()) {
        output.writeMessage(6, element);
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq element : getGetmsgreqList()) {
        output.writeMessage(7, element);
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasPayload()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(1, getPayload());
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq element : getSyncreqList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(6, element);
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq element : getGetmsgreqList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(7, element);
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GroupUpPacket mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            setPayload(input.readUInt32());
            break;
          }
          case 50: {
            com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq value = new com.huajiao.comm.protobuf.GroupChatProto.GroupSyncReq();
            input.readMessage(value);
            addSyncreq(value);
            break;
          }
          case 58: {
            com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq value = new com.huajiao.comm.protobuf.GroupChatProto.GroupMessageReq();
            input.readMessage(value);
            addGetmsgreq(value);
            break;
          }
        }
      }
    }

    public static GroupUpPacket parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GroupUpPacket) (new GroupUpPacket().mergeFrom(data));
    }

    public static GroupUpPacket parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GroupUpPacket().mergeFrom(input);
    }

  }

  @SuppressWarnings("hiding")
  public static final class GroupDownPacket extends
      com.google.protobuf.micro.MessageMicro {
    public GroupDownPacket() {}

    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean hasResult;
    private int result_ = 0;
    public int getResult() { return result_; }
    public boolean hasResult() { return hasResult; }
    public GroupDownPacket setResult(int value) {
      hasResult = true;
      result_ = value;
      return this;
    }
    public GroupDownPacket clearResult() {
      hasResult = false;
      result_ = 0;
      return this;
    }

    // required uint32 payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private boolean hasPayload;
    private int payload_ = 0;
    public int getPayload() { return payload_; }
    public boolean hasPayload() { return hasPayload; }
    public GroupDownPacket setPayload(int value) {
      hasPayload = true;
      payload_ = value;
      return this;
    }
    public GroupDownPacket clearPayload() {
      hasPayload = false;
      payload_ = 0;
      return this;
    }

    // optional string reason = 3;
    public static final int REASON_FIELD_NUMBER = 3;
    private boolean hasReason;
    private java.lang.String reason_ = "";
    public java.lang.String getReason() { return reason_; }
    public boolean hasReason() { return hasReason; }
    public GroupDownPacket setReason(java.lang.String value) {
      hasReason = true;
      reason_ = value;
      return this;
    }
    public GroupDownPacket clearReason() {
      hasReason = false;
      reason_ = "";
      return this;
    }

    // optional int32 sleep = 4 [default = 0];
    public static final int SLEEP_FIELD_NUMBER = 4;
    private boolean hasSleep;
    private int sleep_ = 0;
    public int getSleep() { return sleep_; }
    public boolean hasSleep() { return hasSleep; }
    public GroupDownPacket setSleep(int value) {
      hasSleep = true;
      sleep_ = value;
      return this;
    }
    public GroupDownPacket clearSleep() {
      hasSleep = false;
      sleep_ = 0;
      return this;
    }

    // repeated .pb.GroupNotify newmsgnotify = 5;
    public static final int NEWMSGNOTIFY_FIELD_NUMBER = 5;
    private java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupNotify> newmsgnotify_ =
      java.util.Collections.emptyList();
    public java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupNotify> getNewmsgnotifyList() {
      return newmsgnotify_;
    }
    public int getNewmsgnotifyCount() { return newmsgnotify_.size(); }
    public com.huajiao.comm.protobuf.GroupChatProto.GroupNotify getNewmsgnotify(int index) {
      return newmsgnotify_.get(index);
    }
    public GroupDownPacket setNewmsgnotify(int index, com.huajiao.comm.protobuf.GroupChatProto.GroupNotify value) {
      if (value == null) {
        throw new NullPointerException();
      }
      newmsgnotify_.set(index, value);
      return this;
    }
    public GroupDownPacket addNewmsgnotify(com.huajiao.comm.protobuf.GroupChatProto.GroupNotify value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (newmsgnotify_.isEmpty()) {
        newmsgnotify_ = new java.util.ArrayList<com.huajiao.comm.protobuf.GroupChatProto.GroupNotify>();
      }
      newmsgnotify_.add(value);
      return this;
    }
    public GroupDownPacket clearNewmsgnotify() {
      newmsgnotify_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated .pb.GroupInfo syncresp = 6;
    public static final int SYNCRESP_FIELD_NUMBER = 6;
    private java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupInfo> syncresp_ =
      java.util.Collections.emptyList();
    public java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupInfo> getSyncrespList() {
      return syncresp_;
    }
    public int getSyncrespCount() { return syncresp_.size(); }
    public com.huajiao.comm.protobuf.GroupChatProto.GroupInfo getSyncresp(int index) {
      return syncresp_.get(index);
    }
    public GroupDownPacket setSyncresp(int index, com.huajiao.comm.protobuf.GroupChatProto.GroupInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      syncresp_.set(index, value);
      return this;
    }
    public GroupDownPacket addSyncresp(com.huajiao.comm.protobuf.GroupChatProto.GroupInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (syncresp_.isEmpty()) {
        syncresp_ = new java.util.ArrayList<com.huajiao.comm.protobuf.GroupChatProto.GroupInfo>();
      }
      syncresp_.add(value);
      return this;
    }
    public GroupDownPacket clearSyncresp() {
      syncresp_ = java.util.Collections.emptyList();
      return this;
    }

    // repeated .pb.GroupMessageResp getmsgresp = 7;
    public static final int GETMSGRESP_FIELD_NUMBER = 7;
    private java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp> getmsgresp_ =
      java.util.Collections.emptyList();
    public java.util.List<com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp> getGetmsgrespList() {
      return getmsgresp_;
    }
    public int getGetmsgrespCount() { return getmsgresp_.size(); }
    public com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp getGetmsgresp(int index) {
      return getmsgresp_.get(index);
    }
    public GroupDownPacket setGetmsgresp(int index, com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      getmsgresp_.set(index, value);
      return this;
    }
    public GroupDownPacket addGetmsgresp(com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (getmsgresp_.isEmpty()) {
        getmsgresp_ = new java.util.ArrayList<com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp>();
      }
      getmsgresp_.add(value);
      return this;
    }
    public GroupDownPacket clearGetmsgresp() {
      getmsgresp_ = java.util.Collections.emptyList();
      return this;
    }

    public final GroupDownPacket clear() {
      clearResult();
      clearPayload();
      clearReason();
      clearSleep();
      clearNewmsgnotify();
      clearSyncresp();
      clearGetmsgresp();
      cachedSize = -1;
      return this;
    }

    public final boolean isInitialized() {
      if (!hasResult) return false;
      if (!hasPayload) return false;
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupNotify element : getNewmsgnotifyList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupInfo element : getSyncrespList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp element : getGetmsgrespList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.micro.CodedOutputStreamMicro output)
                        throws java.io.IOException {
      if (hasResult()) {
        output.writeInt32(1, getResult());
      }
      if (hasPayload()) {
        output.writeUInt32(2, getPayload());
      }
      if (hasReason()) {
        output.writeString(3, getReason());
      }
      if (hasSleep()) {
        output.writeInt32(4, getSleep());
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupNotify element : getNewmsgnotifyList()) {
        output.writeMessage(5, element);
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupInfo element : getSyncrespList()) {
        output.writeMessage(6, element);
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp element : getGetmsgrespList()) {
        output.writeMessage(7, element);
      }
    }

    private int cachedSize = -1;
    @Override
    public int getCachedSize() {
      if (cachedSize < 0) {
        // getSerializedSize sets cachedSize
        getSerializedSize();
      }
      return cachedSize;
    }

    @Override
    public int getSerializedSize() {
      int size = 0;
      if (hasResult()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt32Size(1, getResult());
      }
      if (hasPayload()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeUInt32Size(2, getPayload());
      }
      if (hasReason()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeStringSize(3, getReason());
      }
      if (hasSleep()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeInt32Size(4, getSleep());
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupNotify element : getNewmsgnotifyList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(5, element);
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupInfo element : getSyncrespList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(6, element);
      }
      for (com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp element : getGetmsgrespList()) {
        size += com.google.protobuf.micro.CodedOutputStreamMicro
          .computeMessageSize(7, element);
      }
      cachedSize = size;
      return size;
    }

    @Override
    public GroupDownPacket mergeFrom(
        com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            setResult(input.readInt32());
            break;
          }
          case 16: {
            setPayload(input.readUInt32());
            break;
          }
          case 26: {
            setReason(input.readString());
            break;
          }
          case 32: {
            setSleep(input.readInt32());
            break;
          }
          case 42: {
            com.huajiao.comm.protobuf.GroupChatProto.GroupNotify value = new com.huajiao.comm.protobuf.GroupChatProto.GroupNotify();
            input.readMessage(value);
            addNewmsgnotify(value);
            break;
          }
          case 50: {
            com.huajiao.comm.protobuf.GroupChatProto.GroupInfo value = new com.huajiao.comm.protobuf.GroupChatProto.GroupInfo();
            input.readMessage(value);
            addSyncresp(value);
            break;
          }
          case 58: {
            com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp value = new com.huajiao.comm.protobuf.GroupChatProto.GroupMessageResp();
            input.readMessage(value);
            addGetmsgresp(value);
            break;
          }
        }
      }
    }

    public static GroupDownPacket parseFrom(byte[] data)
        throws com.google.protobuf.micro.InvalidProtocolBufferMicroException {
      return (GroupDownPacket) (new GroupDownPacket().mergeFrom(data));
    }

    public static GroupDownPacket parseFrom(
            com.google.protobuf.micro.CodedInputStreamMicro input)
        throws java.io.IOException {
      return new GroupDownPacket().mergeFrom(input);
    }

  }

}
