// Code generated by protoc-gen-go.
// source: groupchat.proto
// DO NOT EDIT!

package pb

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// group notification
type GroupNotify struct {
	Groupid          *string `protobuf:"bytes,1,req,name=groupid" json:"groupid,omitempty"`
	Msgid            *uint64 `protobuf:"varint,2,req,name=msgid" json:"msgid,omitempty"`
	Summary          *string `protobuf:"bytes,3,opt,name=summary" json:"summary,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupNotify) Reset()                    { *m = GroupNotify{} }
func (m *GroupNotify) String() string            { return proto.CompactTextString(m) }
func (*GroupNotify) ProtoMessage()               {}
func (*GroupNotify) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *GroupNotify) GetGroupid() string {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return ""
}

func (m *GroupNotify) GetMsgid() uint64 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return 0
}

func (m *GroupNotify) GetSummary() string {
	if m != nil && m.Summary != nil {
		return *m.Summary
	}
	return ""
}

//
// get group message request
type GroupMessageReq struct {
	Groupid          *string `protobuf:"bytes,1,req,name=groupid" json:"groupid,omitempty"`
	Traceid          *string `protobuf:"bytes,2,req,name=traceid" json:"traceid,omitempty"`
	Startid          *uint64 `protobuf:"varint,3,opt,name=startid" json:"startid,omitempty"`
	Offset           *int32  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupMessageReq) Reset()                    { *m = GroupMessageReq{} }
func (m *GroupMessageReq) String() string            { return proto.CompactTextString(m) }
func (*GroupMessageReq) ProtoMessage()               {}
func (*GroupMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GroupMessageReq) GetGroupid() string {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return ""
}

func (m *GroupMessageReq) GetTraceid() string {
	if m != nil && m.Traceid != nil {
		return *m.Traceid
	}
	return ""
}

func (m *GroupMessageReq) GetStartid() uint64 {
	if m != nil && m.Startid != nil {
		return *m.Startid
	}
	return 0
}

func (m *GroupMessageReq) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

//
// group message
type GroupMessage struct {
	Msgid            *uint64 `protobuf:"varint,1,req,name=msgid" json:"msgid,omitempty"`
	Content          *string `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	Sendtime         *int64  `protobuf:"varint,3,opt,name=sendtime" json:"sendtime,omitempty"`
	Sender           *string `protobuf:"bytes,4,opt,name=sender" json:"sender,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupMessage) Reset()                    { *m = GroupMessage{} }
func (m *GroupMessage) String() string            { return proto.CompactTextString(m) }
func (*GroupMessage) ProtoMessage()               {}
func (*GroupMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GroupMessage) GetMsgid() uint64 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return 0
}

func (m *GroupMessage) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *GroupMessage) GetSendtime() int64 {
	if m != nil && m.Sendtime != nil {
		return *m.Sendtime
	}
	return 0
}

func (m *GroupMessage) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

//
// get group message response
type GroupMessageResp struct {
	Groupid          *string         `protobuf:"bytes,1,req,name=groupid" json:"groupid,omitempty"`
	Traceid          *string         `protobuf:"bytes,2,req,name=traceid" json:"traceid,omitempty"`
	Msglist          []*GroupMessage `protobuf:"bytes,3,rep,name=msglist" json:"msglist,omitempty"`
	Maxid            *uint64         `protobuf:"varint,4,opt,name=maxid" json:"maxid,omitempty"`
	Version          *int64          `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GroupMessageResp) Reset()                    { *m = GroupMessageResp{} }
func (m *GroupMessageResp) String() string            { return proto.CompactTextString(m) }
func (*GroupMessageResp) ProtoMessage()               {}
func (*GroupMessageResp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GroupMessageResp) GetGroupid() string {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return ""
}

func (m *GroupMessageResp) GetTraceid() string {
	if m != nil && m.Traceid != nil {
		return *m.Traceid
	}
	return ""
}

func (m *GroupMessageResp) GetMsglist() []*GroupMessage {
	if m != nil {
		return m.Msglist
	}
	return nil
}

func (m *GroupMessageResp) GetMaxid() uint64 {
	if m != nil && m.Maxid != nil {
		return *m.Maxid
	}
	return 0
}

func (m *GroupMessageResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

//
// sync user groups request
type GroupSyncReq struct {
	Groupid          *string `protobuf:"bytes,1,req,name=groupid" json:"groupid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupSyncReq) Reset()                    { *m = GroupSyncReq{} }
func (m *GroupSyncReq) String() string            { return proto.CompactTextString(m) }
func (*GroupSyncReq) ProtoMessage()               {}
func (*GroupSyncReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *GroupSyncReq) GetGroupid() string {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return ""
}

//
// 群信息
type GroupInfo struct {
	Groupid          *string `protobuf:"bytes,1,req,name=groupid" json:"groupid,omitempty"`
	Maxid            *uint64 `protobuf:"varint,2,opt,name=maxid" json:"maxid,omitempty"`
	Version          *int64  `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Startid          *uint64 `protobuf:"varint,4,opt,name=startid" json:"startid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupInfo) Reset()                    { *m = GroupInfo{} }
func (m *GroupInfo) String() string            { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()               {}
func (*GroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *GroupInfo) GetGroupid() string {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return ""
}

func (m *GroupInfo) GetMaxid() uint64 {
	if m != nil && m.Maxid != nil {
		return *m.Maxid
	}
	return 0
}

func (m *GroupInfo) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *GroupInfo) GetStartid() uint64 {
	if m != nil && m.Startid != nil {
		return *m.Startid
	}
	return 0
}

// *
// payloadtype options:
// 108 -- sync group request
// 109 -- getmsgreq
type GroupUpPacket struct {
	Payload          *uint32            `protobuf:"varint,1,req,name=payload" json:"payload,omitempty"`
	Syncreq          []*GroupSyncReq    `protobuf:"bytes,6,rep,name=syncreq" json:"syncreq,omitempty"`
	Getmsgreq        []*GroupMessageReq `protobuf:"bytes,7,rep,name=getmsgreq" json:"getmsgreq,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GroupUpPacket) Reset()                    { *m = GroupUpPacket{} }
func (m *GroupUpPacket) String() string            { return proto.CompactTextString(m) }
func (*GroupUpPacket) ProtoMessage()               {}
func (*GroupUpPacket) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GroupUpPacket) GetPayload() uint32 {
	if m != nil && m.Payload != nil {
		return *m.Payload
	}
	return 0
}

func (m *GroupUpPacket) GetSyncreq() []*GroupSyncReq {
	if m != nil {
		return m.Syncreq
	}
	return nil
}

func (m *GroupUpPacket) GetGetmsgreq() []*GroupMessageReq {
	if m != nil {
		return m.Getmsgreq
	}
	return nil
}

// *
// payloadtype options:
// 108 -- sync group response
// 109 -- getmsgresp;
// 200 -- nesmsgnotify
// [result]
// 0     -- successful
type GroupDownPacket struct {
	Result           *int32              `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	Payload          *uint32             `protobuf:"varint,2,req,name=payload" json:"payload,omitempty"`
	Reason           *string             `protobuf:"bytes,3,opt,name=reason" json:"reason,omitempty"`
	Sleep            *int32              `protobuf:"varint,4,opt,name=sleep,def=0" json:"sleep,omitempty"`
	Newmsgnotify     []*GroupNotify      `protobuf:"bytes,5,rep,name=newmsgnotify" json:"newmsgnotify,omitempty"`
	Syncresp         []*GroupInfo        `protobuf:"bytes,6,rep,name=syncresp" json:"syncresp,omitempty"`
	Getmsgresp       []*GroupMessageResp `protobuf:"bytes,7,rep,name=getmsgresp" json:"getmsgresp,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GroupDownPacket) Reset()                    { *m = GroupDownPacket{} }
func (m *GroupDownPacket) String() string            { return proto.CompactTextString(m) }
func (*GroupDownPacket) ProtoMessage()               {}
func (*GroupDownPacket) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

const Default_GroupDownPacket_Sleep int32 = 0

func (m *GroupDownPacket) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *GroupDownPacket) GetPayload() uint32 {
	if m != nil && m.Payload != nil {
		return *m.Payload
	}
	return 0
}

func (m *GroupDownPacket) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *GroupDownPacket) GetSleep() int32 {
	if m != nil && m.Sleep != nil {
		return *m.Sleep
	}
	return Default_GroupDownPacket_Sleep
}

func (m *GroupDownPacket) GetNewmsgnotify() []*GroupNotify {
	if m != nil {
		return m.Newmsgnotify
	}
	return nil
}

func (m *GroupDownPacket) GetSyncresp() []*GroupInfo {
	if m != nil {
		return m.Syncresp
	}
	return nil
}

func (m *GroupDownPacket) GetGetmsgresp() []*GroupMessageResp {
	if m != nil {
		return m.Getmsgresp
	}
	return nil
}

func init() {
	proto.RegisterType((*GroupNotify)(nil), "pb.GroupNotify")
	proto.RegisterType((*GroupMessageReq)(nil), "pb.GroupMessageReq")
	proto.RegisterType((*GroupMessage)(nil), "pb.GroupMessage")
	proto.RegisterType((*GroupMessageResp)(nil), "pb.GroupMessageResp")
	proto.RegisterType((*GroupSyncReq)(nil), "pb.GroupSyncReq")
	proto.RegisterType((*GroupInfo)(nil), "pb.GroupInfo")
	proto.RegisterType((*GroupUpPacket)(nil), "pb.GroupUpPacket")
	proto.RegisterType((*GroupDownPacket)(nil), "pb.GroupDownPacket")
}

var fileDescriptor2 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x65, 0x27, 0x6e, 0xf0, 0xb4, 0x69, 0x22, 0xc3, 0xc1, 0x9c, 0x5a, 0x2c, 0x81, 0x22,
	0x21, 0x59, 0x88, 0x23, 0x07, 0x0e, 0x05, 0x09, 0x71, 0x28, 0x8a, 0xf8, 0xf3, 0x00, 0x1b, 0x77,
	0x9c, 0x9a, 0xc6, 0xbb, 0xdb, 0xdd, 0x35, 0x21, 0x2f, 0xc8, 0x73, 0x31, 0x3b, 0xde, 0x94, 0x90,
	0xe4, 0xd0, 0x5b, 0x76, 0xf2, 0xf9, 0x37, 0xdf, 0x37, 0xb3, 0x0b, 0x93, 0xa5, 0x51, 0x9d, 0xae,
	0x6e, 0x85, 0x2b, 0xb5, 0x51, 0x4e, 0x65, 0xb1, 0x5e, 0x14, 0xef, 0xe1, 0xf4, 0x93, 0x2f, 0x7f,
	0x51, 0xae, 0xa9, 0x37, 0xd9, 0x04, 0x46, 0xac, 0x6a, 0x6e, 0xf2, 0xe8, 0x32, 0x9e, 0xa5, 0xd9,
	0x18, 0x92, 0xd6, 0x2e, 0xe9, 0x18, 0xd3, 0x71, 0xe8, 0xff, 0xb7, 0x5d, 0xdb, 0x0a, 0xb3, 0xc9,
	0x07, 0x97, 0xd1, 0x2c, 0x2d, 0xbe, 0xc3, 0x84, 0xbf, 0xbf, 0x46, 0x6b, 0xc5, 0x12, 0xbf, 0xe2,
	0xfd, 0x21, 0x83, 0x0a, 0xce, 0x88, 0x0a, 0x03, 0x85, 0x0b, 0xd6, 0x09, 0xe3, 0xa8, 0xe0, 0x29,
	0xc3, 0xec, 0x1c, 0x4e, 0x54, 0x5d, 0x5b, 0x74, 0xf9, 0x90, 0xce, 0x49, 0x31, 0x87, 0xb3, 0x5d,
	0xea, 0x3f, 0x17, 0xd1, 0xd6, 0x45, 0xa5, 0xa4, 0x43, 0xe9, 0x02, 0x70, 0x0a, 0x4f, 0x2c, 0xca,
	0x1b, 0xd7, 0xb4, 0xc8, 0xc4, 0x81, 0x27, 0xfa, 0x0a, 0x1a, 0x26, 0xa6, 0xc5, 0x1a, 0xa6, 0xff,
	0xfb, 0xb4, 0xfa, 0x11, 0x46, 0x5f, 0xc0, 0x88, 0xfa, 0xae, 0x1a, 0xeb, 0x08, 0x3b, 0x98, 0x9d,
	0xbe, 0x9d, 0x96, 0x7a, 0x51, 0x1e, 0x58, 0x13, 0xbf, 0xe9, 0x8b, 0x21, 0x27, 0x21, 0xc4, 0x2f,
	0x34, 0xb6, 0x51, 0x32, 0x4f, 0xbc, 0x91, 0xe2, 0x22, 0x44, 0xf9, 0xb6, 0x91, 0xd5, 0xb1, 0xe9,
	0x14, 0xd7, 0x90, 0xb2, 0xe0, 0xb3, 0xac, 0xd5, 0xf1, 0xf9, 0x33, 0x3e, 0xde, 0xc7, 0xf7, 0x39,
	0x77, 0x46, 0xc9, 0x06, 0x8a, 0x3b, 0x18, 0x33, 0xee, 0x87, 0x9e, 0x8b, 0xea, 0x0e, 0x9d, 0x57,
	0x68, 0xb1, 0x59, 0x29, 0xd1, 0x23, 0xc7, 0x3e, 0x94, 0x25, 0x33, 0x06, 0xef, 0xf3, 0x93, 0xbd,
	0x50, 0x5b, 0x93, 0xaf, 0x20, 0x5d, 0xa2, 0xa3, 0xe8, 0x5e, 0x34, 0x62, 0xd1, 0xd3, 0xfd, 0xe4,
	0xa4, 0x2b, 0xfe, 0x44, 0x61, 0xfd, 0x1f, 0xd5, 0x5a, 0x86, 0x7e, 0x34, 0x79, 0x83, 0xb6, 0x5b,
	0x39, 0x6e, 0x97, 0xec, 0xf6, 0x8f, 0xb9, 0x3f, 0x0b, 0x84, 0x0d, 0x11, 0xfc, 0xf2, 0x12, 0xbb,
	0x42, 0xd4, 0xfd, 0xee, 0xdf, 0x45, 0x6f, 0xb2, 0x97, 0x70, 0x26, 0x71, 0x4d, 0xed, 0x25, 0xdf,
	0x4a, 0x9a, 0xa4, 0x77, 0x30, 0x79, 0x70, 0x10, 0x2e, 0xeb, 0x05, 0x6d, 0x9d, 0x83, 0x58, 0x1d,
	0x92, 0x8c, 0x1f, 0x24, 0x3c, 0xcd, 0x19, 0xc0, 0x36, 0x06, 0x49, 0xfa, 0x1c, 0xcf, 0x0e, 0x73,
	0x58, 0x7d, 0xf5, 0x1a, 0x9e, 0x57, 0xaa, 0x2d, 0x6f, 0x3b, 0xf1, 0xb3, 0x11, 0xaa, 0xa4, 0xdf,
	0x6d, 0xff, 0x48, 0x16, 0x5d, 0x7d, 0x75, 0xce, 0xf2, 0x0f, 0xf4, 0x70, 0xe6, 0xbe, 0xf4, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xf0, 0xe1, 0xbb, 0x10, 0x49, 0x03, 0x00, 0x00,
}
